name: docs

on:
  release:
    types: [published]
    tags:
      - 'v*'

jobs:
  docs:
    name: Create docs for GitHub Pages 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r req-doc.txt
        
    - name: Sphinx Build
      run: |
        cd docs
        sphinx-build -b html . _build

    - name: Upload to Github Pages
      uses: crazy-max/ghaction-github-pages@v2.4.1
      with:
        build_dir: docs/_build/
        target_branch: gh-pages
        jekyll: false
        committer: Wojciech Wentland <wojciech.wentland@int.pl>
        author: Wojciech Wentland <wojciech.wentland@int.pl>
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
